services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always
    networks:
      - dbnet
    expose:
      - 8088
    ports:
      - "80:8088"
    volumes:
      - ./KBR_SPORT/static:/app/www/KBR_SPORT/static
      - ./KBR_SPORT/media:/app/www/KBR_SPORT/media
      - ./KBR_SPORT/logs:/app/www/KBR_SPORT/logs
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - kbr_sport

  kbr_sport:
    build: ./KBR_SPORT
    image: kbr_sport
    container_name: kbr_sport
    restart: always
    command: 'gunicorn -c gunicorn.py KBR_SPORT.wsgi'
    env_file:
      - .env
    networks:
      - dbnet
    volumes:
      - ./KBR_SPORT:/app/www/KBR_SPORT
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    container_name: psgr
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - dbnet

networks:
  dbnet:
    driver: bridge

volumes:
  postgres-data:
