# Generated by Django 4.2.1 on 2025-02-14 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sport',
            name='avail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avail', to='sport.avi', verbose_name='Статус товара'),
        ),
        migrations.AddField(
            model_name='sport',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post', to='sport.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='sport',
            name='photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='sport.photos'),
        ),
        migrations.AddField(
            model_name='sport',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='sport.tagpost', verbose_name='Теги'),
        ),
        migrations.AddIndex(
            model_name='sport',
            index=models.Index(fields=['-time_create'], name='sport_sport_time_cr_72e8f0_idx'),
        ),
    ]
